"""size bytes

Revision ID: c6495ad340ab
Revises: 80ba9876391b
Create Date: 2025-02-28 14:47:04.359700

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c6495ad340ab"
down_revision: Union[str, None] = "80ba9876391b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("files", "size", new_column_name="size_bytes")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("files", "size_bytes", new_column_name="size")
    # ### end Alembic commands ###
