"""empty message

Revision ID: dd9073374d41
Revises: c6495ad340ab
Create Date: 2025-04-15 22:07:38.733379

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "dd9073374d41"
down_revision: Union[str, None] = "c6495ad340ab"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "files",
        "user_id",
        existing_type=sa.VARCHAR(),
        type_=sa.UUID(),
        existing_nullable=False,
        postgresql_using="user_id::uuid",
    )

    op.alter_column(
        "files",
        "filename",
        existing_type=sa.String(),
        type_=sa.String(length=255),
    )

    op.alter_column(
        "files",
        "extension",
        existing_type=sa.String(),
        type_=sa.String(length=10),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "files",
        "user_id",
        existing_type=sa.UUID(),
        type_=sa.VARCHAR(),
        existing_nullable=False,
    )

    op.alter_column(
        "files",
        "filename",
        existing_type=sa.String(length=255),
        type_=sa.String(),
    )

    op.alter_column(
        "files",
        "extension",
        existing_type=sa.String(length=10),
        type_=sa.String(),
    )
    # ### end Alembic commands ###
